#!/bin/bash

# export CASSANDRA_HOME=/opt/apache-cassandra-2.1.0

export CURRENT_IP=`hostname -i`

envsubst < ${CASSANDRA_HOME}/conf/cassandra.yaml.template > ${CASSANDRA_HOME}/conf/cassandra.yaml

${CASSANDRA_HOME}/bin/cassandra