#!/bin/bash

export CASSANDRA_HOME=/opt/apache-cassandra-3.1.1

export CURRENT_IP=`hostname -i`

envsubst < ${CASSANDRA_HOME}/conf/cassandra.yaml.template > ${CASSANDRA_HOME}/conf/cassandra.yaml

${CASSANDRA_HOME}/bin/cassandra
